SELECT AVG(LENGTH(WORD)), COUNT(WORD), SUBREDDIT 
FROM TEST.WORDS
WHERE LENGTH(WORD) < 20
    AND LENGTH(WORD) > 3
    AND WORD NOT LIKE "%href%"
    AND WORD NOT LIKE "%http%"
GROUP BY SUBREDDIT
ORDER by AVG(LENGTH(WORD)) DESC;